<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-27T05:20:34 EDT" name="TF_TestNg" finished-at="2022-04-27T05:21:00 EDT" duration-ms="25977">
    <groups>
    </groups>
    <test started-at="2022-04-27T05:20:34 EDT" name="Validating_Add_and_display_category" finished-at="2022-04-27T05:21:00 EDT" duration-ms="25977">
      <class name="com.TestPages.PracticalTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:20:34 EDT" name="setUp" finished-at="2022-04-27T05:20:45 EDT" duration-ms="10596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyTestPageTitle()[pri:0, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:20:45 EDT" name="verifyTestPageTitle" finished-at="2022-04-27T05:20:45 EDT" duration-ms="28" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[NSS-TODO List v 1.1 expected [] but found [wrong title]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: NSS-TODO List v 1.1 expected [] but found [wrong title]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.TestPages.PracticalTest.verifyTestPageTitle(PracticalTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestPageTitle -->
        <test-method signature="verifyTestPageHeader()[pri:1, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:20:45 EDT" name="verifyTestPageHeader" finished-at="2022-04-27T05:20:45 EDT" duration-ms="70" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[NSS-TODO List v 1.1 expected [NSS-TODO List v 1.1] but found [wrong page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: NSS-TODO List v 1.1 expected [NSS-TODO List v 1.1] but found [wrong page]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.TestPages.PracticalTest.verifyTestPageHeader(PracticalTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestPageHeader -->
        <test-method signature="addNewCategory(java.lang.String,int)[pri:2, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:20:45 EDT" name="addNewCategory" finished-at="2022-04-27T05:20:52 EDT" duration-ms="6486" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestNGTest25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[100]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCategory -->
        <test-method signature="verifyAddAndDisplayCategory(java.lang.String)[pri:3, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:20:52 EDT" name="verifyAddAndDisplayCategory" finished-at="2022-04-27T05:21:00 EDT" duration-ms="8417" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestNGTest25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddAndDisplayCategory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.TestPages.PracticalTest@6babf3bf]" started-at="2022-04-27T05:21:00 EDT" name="tearDown" finished-at="2022-04-27T05:21:00 EDT" duration-ms="302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.TestPages.PracticalTest -->
    </test> <!-- Validating_Add_and_display_category -->
  </suite> <!-- TF_TestNg -->
</testng-results>
